INSERT INTO category (id, name, parent_id) VALUES (1, 'Real Estate', NULL);
INSERT INTO category (id, name, parent_id) VALUES (2, 'Transport', NULL);
INSERT INTO category (id, name, parent_id) VALUES (3, 'Jobs', NULL);
INSERT INTO category (id, name, parent_id) VALUES (4, 'Services', NULL);
INSERT INTO category (id, name, parent_id) VALUES (5, 'Animals & Pets', NULL);
INSERT INTO category (id, name, parent_id) VALUES (6, 'Home & Garden', NULL);
INSERT INTO category (id, name, parent_id) VALUES (7, 'Electronics', NULL);
INSERT INTO category (id, name, parent_id) VALUES (8, 'Kids & Baby', NULL);
INSERT INTO category (id, name, parent_id) VALUES (9, 'Fashion & Style', NULL);
INSERT INTO category (id, name, parent_id) VALUES (10, 'Hobbies & Sports', NULL);
INSERT INTO category (id, name, parent_id) VALUES (11, 'Equipment & Machinery', NULL);
INSERT INTO category (id, name, parent_id) VALUES (12, 'Exchange & Barter', NULL);
INSERT INTO category (id, name, parent_id) VALUES (13, 'Apartments for Sale', 1);
INSERT INTO category (id, name, parent_id) VALUES (14, 'Apartments for Rent', 1);
INSERT INTO category (id, name, parent_id) VALUES (15, 'Land Plots', 1);
INSERT INTO category (id, name, parent_id) VALUES (16, 'Commercial Property', 1);
INSERT INTO category (id, name, parent_id) VALUES (17, 'Garages & Parking', 1);
INSERT INTO category (id, name, parent_id) VALUES (18, 'Cars', 2);
INSERT INTO category (id, name, parent_id) VALUES (19, 'Motorcycles & Scooters', 2);
INSERT INTO category (id, name, parent_id) VALUES (20, 'Trucks & Buses', 2);
INSERT INTO category (id, name, parent_id) VALUES (21, 'Vehicle Parts & Accessories', 2);
INSERT INTO category (id, name, parent_id) VALUES (22, 'Vacancies', 3);
INSERT INTO category (id, name, parent_id) VALUES (23, 'Job Seekers', 3);
INSERT INTO category (id, name, parent_id) VALUES (24, 'Repair Services', 4);
INSERT INTO category (id, name, parent_id) VALUES (25, 'Moving Services', 4);
INSERT INTO category (id, name, parent_id) VALUES (26, 'Cleaning Services', 4);
INSERT INTO category (id, name, parent_id) VALUES (27, 'Dogs', 5);
INSERT INTO category (id, name, parent_id) VALUES (28, 'Cats', 5);
INSERT INTO category (id, name, parent_id) VALUES (29, 'Birds', 5);
INSERT INTO category (id, name, parent_id) VALUES (30, 'Other Pets', 5);
INSERT INTO category (id, name, parent_id) VALUES (31, 'Furniture', 6);
INSERT INTO category (id, name, parent_id) VALUES (32, 'Kitchen', 6);
INSERT INTO category (id, name, parent_id) VALUES (33, 'Renovation & Repair', 6);
INSERT INTO category (id, name, parent_id) VALUES (34, 'Phones & Accessories', 7);
INSERT INTO category (id, name, parent_id) VALUES (35, 'Computers', 7);
INSERT INTO category (id, name, parent_id) VALUES (36, 'TVs & Audio', 7);
INSERT INTO category (id, name, parent_id) VALUES (37, 'Toys', 8);
INSERT INTO category (id, name, parent_id) VALUES (38, 'Baby Equipment', 8);
INSERT INTO category (id, name, parent_id) VALUES (39, 'Kids' Clothes', 8);
INSERT INTO category (id, name, parent_id) VALUES (40, 'Men's Clothing', 9);
INSERT INTO category (id, name, parent_id) VALUES (41, 'Women's Clothing', 9);
INSERT INTO category (id, name, parent_id) VALUES (42, 'Shoes & Accessories', 9);
INSERT INTO category (id, name, parent_id) VALUES (43, 'Fitness Equipment', 10);
INSERT INTO category (id, name, parent_id) VALUES (44, 'Outdoor Gear', 10);
INSERT INTO category (id, name, parent_id) VALUES (45, 'Musical Instruments', 10);
INSERT INTO category (id, name, parent_id) VALUES (46, 'Industrial Equipment', 11);
INSERT INTO category (id, name, parent_id) VALUES (47, 'Agricultural Machinery', 11);
INSERT INTO category (id, name, parent_id) VALUES (48, 'Barter Deals', 12);