server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/olx_db
    username: abdulbosit_admin
    password: abdulbosit_developer_2025

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false  # Pastda logging orqali chiroyli chiqariladi
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: abdulbositAbdurahimov70@gmail.com
    password: 'cphf yxno yydk sufr'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

springdoc:
  swagger-ui:
    path: /swagger-ui.html

olx:
  app:
    base-folder: /root/abdulbosit/OLX-backend/olx-doc

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.type.descriptor.sql: TRACE
    uz.pdp.backend.olxapp: DEBUG

  file:
    name: /root/abdulbosit/OLX-backend/olx-log/  # ? Fayl serverda shu yerga yoziladi (agar yo?q bo?lsa o?zi yaratiladi)

  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [requestId=%X{requestId}] %-5level %logger{36} - %msg%n"
    console: "%d{HH:mm:ss.SSS} [requestId=%X{requestId}] %-5level [%thread] %logger{36} - %msg%n"
